### ISSUE TITLE
Core.lua Script Ran Too Long

### ISSUE THREAD

**Issue by joeymagz** [FailcoderAddons/supervillain-ui#106]
Receiving script ran too long errors after 7.2.5 during any instanced combat.

Reported by:
Joopeter during bg's

Reproduced the error myself inside of ToS.

Core.lua is fixed. Registry.lua is throwing errors still though.

**Comment by joeymagz** [comment]
Keeping this open in case there are further reports.

**Comment by joeymagz** [comment]
I raid ToS again tonight, if I don't receive any "script ran too long" errors, then I will close this.

**Comment by joeymagz** [comment]
Registry.lua runs too long, modifying first entry.

**Comment by immortaltech** [comment]
Leaving warlock class hall give me this erro everytime.

Message: ...erface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:440: script ran too long
Time: 08/12/17 14:21:50
Count: 2
Stack: ...erface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:440: script ran too longInterface\SharedXML\SharedBasicControls.lua:204: in function `origErrorHandler'
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
...erface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:440: in function <...erface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:436>

Locals: errorMessage = "...erface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Registry.lua:440: script ran too long"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0
