### ISSUE TITLE
Artifact Bar

### ISSUE THREAD

**Issue by immortaltech** [FailcoderAddons/supervillain-ui#110]
Default artifact bar showing when i mouseover my chat
![aaaaaaaaaaaaaaaaaart](https://user-images.githubusercontent.com/7233566/29241834-234f04be-7f58-11e7-85d7-da4f73c87229.jpg)

**Comment by joeymagz** [comment]
Do you mean that the tooltip displays when you mouseover chat, or does the Artifact Bar report display on the bottom when you mouseover chat?

**Comment by finalsliver** [comment]
I don't recognise the tooltip style, do you have another addon giving such information? 

SVui binds the Artifact bar tooltip to the mouse, and only on hover over. style in general is also different. 

![Artifact bar tooltip](http://i.imgur.com/73VvEal.png)

**Comment by immortaltech** [comment]
Not just the chat, looks like an invisible bar ...
here a little gif to see what im trying to say.
[https://gyazo.com/5daaf44d0e80885eb3beb07bfc17f08a](url)

Removed all other addon, only SVui running

**Comment by joeymagz** [comment]
The gif isn't working for me.

**Comment by immortaltech** [comment]
try to copy/paste, worked fine for me
