### ISSUE TITLE
Guild Roster Profession display issue

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#112]
Looks like it may be a skinning issue, only displayed on the professions section of the roster. 
Present on a clean install from today repo. 2017 - 08 - 14

![profesions roster](http://i.imgur.com/aVkFRuk.png)

**Comment by finalsliver** [comment]
This issue was brought to us by Discord user Futz0r .

**Comment by joeymagz** [comment]
Fixed!
