### ISSUE TITLE
Can we move the quick join toast?

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#118]
Currently the QuickJoinToastButton and it's numerations seem to start offscreen floating just above chat. can't seem to move this in the "/sv move" window. 

Is this something we could add, or atleast move so it doesn't start off screen?

couldn't catch the toast but got an /fstack of the area after
![sample area](http://i.imgur.com/DJxXtIO.jpg)

**Comment by joeymagz** [comment]
Already working on this, but have only been able to move the bell, not the whole toast window... Blizzard is tricking us with those labels! 

I will get this one done though for sure. Very annoying that I have to click on it to find out which friend joined what group.

**Comment by joeymagz** [comment]
Working on this now. I have the popup's moved, just thinking of best way to implement in a Supervillain style!

**Comment by immortaltech** [comment]
Not sure if i should post it in here, but the new toast anchor seems really big for me like the entire screen.
i will take a screenshot when i get home

**Comment by joeymagz** [comment]
You can resize it in the Supervillain options menu > Skins > Quick Join Toast Settings. You can also move it anywhere you want under the Move Frames option.

**Comment by immortaltech** [comment]
I found it, thanks.
