### ISSUE TITLE
Error on load relating to Guild skin

### ISSUE THREAD

**Issue by joev** [FailcoderAddons/supervillain-ui#12]
SKINS [Blizzard_GuildUI]: @(10/27/16 11:57:49) - ...face\AddOns\SVUI_Skins\components\blizzard\guild.lua:524: attempt to call method 'SetStyle' (a nil value)

**Comment by finalsliver** [comment]
![](http://i.imgur.com/OiXo4Jm.png)

![](http://i.imgur.com/brEEenQ.png)

confirmed present in build 9d2d5f3

**Comment by finalsliver** [comment]
![](http://i.imgur.com/du3N1UU.png)
affects skills menu as well. (I'm using Skillet, hence the Different menu

**Comment by finalsliver** [comment]
![](http://i.imgur.com/TXNB3fH.png)
Auction house triggered this one

**Comment by joev** [comment]
Temporarily commented out the SetStyle calls (524 and 550) but I believe @failcoder is looking at a longer term solution so leaving this one open pending his update.

**Comment by joeymagz** [comment]
Closing overall issue since it has been fixed.
