### ISSUE TITLE
AP bar & report numbers may be getting too large?

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#121]
Occurred to me when looking at the artifact bar & report in reference to the honor bar ticket.

Not sure if the following is possible within the reports as they are, or how much work this would actually be.

As we are now about to get a new set of AK levels ingame, should we look at Humanizing the numbers for the AP reports?

As below is my under-developed Druids ap bar. I can't tell how many zero's are in that current AP value.
![APReport](http://i.imgur.com/gd7rcUy.png)

Total AP for all 101 traits is apparently 79,739,892,266,330  [source](https://twitter.com/Binkenstein/status/834609685957222404)

That's a lot of digits. 

Should we consider having the report's print values in a more readable number format

1,000 = 1K
1,000,000 = 1M
1,000,000,000 = 1B
1,000,000,000,000 = 1T

We could possibly break into decimals. best to always round down in such cases. example: 1.2K

**Comment by joeymagz** [comment]
I was already considering this because my next trait is like 7 billion or some nonsense.

**Comment by joeymagz** [comment]
Done!
