### ISSUE TITLE
Achievements Icon size inconsistent

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#129]
Achievement Icons in the achievements window are improperly size. 
Summary page is fine. Icons look to be correct
![summaryPage](http://i.imgur.com/edm1guO.png)

However within any of the sections they seem to be at their minimum size. very difficult to identify
![GeneralPage](http://i.imgur.com/Hd0Whr3.png)

This persists onto the Guild achievements pages

![GuildPage](http://i.imgur.com/NXweo8x.png)

**Comment by immortaltech** [comment]
After leaving/entering any instance its getting smaller.

Logged inside dreadscar rift
![1st](https://user-images.githubusercontent.com/7233566/29976603-f3d15962-8f10-11e7-95e2-178b7a61bf60.jpg)

then zoned out 1st time
![2nd](https://user-images.githubusercontent.com/7233566/29976726-614c42e0-8f11-11e7-994b-919f9e813df5.jpg)

zoned in/out few times 
![2222nd](https://user-images.githubusercontent.com/7233566/29976777-9c2aee52-8f11-11e7-9657-ecf8ac9afb2a.jpg)

**Comment by joeymagz** [comment]
LOL!!  I really like the way the icons change sizes, don't you?

**Comment by joeymagz** [comment]
I'll look into this on the weekend.

**Comment by finalsliver** [comment]
Fresh log in.
![FreshLogIn]https://i.imgur.com/hGs6rS7.jpg)

Walk through pally portal
![PallyPortal](https://i.imgur.com/TqCy20w.jpg)

Walk through portal back to Dalaran
![BackThroughPallyPortal](https://i.imgur.com/WT3mvvM.jpg)

**Comment by finalsliver** [comment]
and another because I can

Stormwind portal after the previous images
![StormwindPortal](https://i.imgur.com/uZGQHNW.png)

**Comment by finalsliver** [comment]
Hearthed back to dalaran and now they are aligned ontop of the frame border??

![hearthedToDalaran](https://i.imgur.com/6cKFtMR.png)

**Comment by finalsliver** [comment]
and lastly a reload resets them to first image size.
