### ISSUE TITLE
Svui no longer passing capslock

### ISSUE THREAD

**Issue by klepp0906** [FailcoderAddons/supervillain-ui#13]
I use caps lock as one of my keybinds and it is no longer working. I assumed it somehow came unbound but it won't register it. The key still works as it picks it up for small/cap letters in the chat box but not with /sv kb

I tried 2 different pcs and 2 different keyboards.

**Comment by joev** [comment]
Working for me. No issues whatsoever. Works on PC and Mac. Something else going on mate. Some other addon perhaps interfering.

**Comment by klepp0906** [comment]
Maybe it was one of the interim versions.  I'll update again and try it

**Comment by klepp0906** [comment]
Found the culprit - I could have swore I checked it/this but apparently not.  

Seems synergy isn't passing capslock properly.  What's odd is that it works for entering upper/lower case letters even in game.. won't register as a bind period though.

Tried with a keyboard attached directly to said pc and it worked so false alarm.

Apologies!

**Comment by joev** [comment]
no problem.
