### ISSUE TITLE
sorta misc stuff

### ISSUE THREAD

**Issue by klepp0906** [FailcoderAddons/supervillain-ui#15]
broken down into individual posts

**Comment by joev** [comment]
Hi @klepp0906 You've been quite for a few weeks :) Good to see you back.

Can I please please please ask that you don't put several issues into one bug report it makes it very difficult for @failcoder and I to split up the work and track what we have and haven't fixed. 

I know it's a pain, but would you please create a seperate issue (with as much information as you can provide) for each of these you've mentioned above so we can knock them down one at a time. 

Many thanks

Joe

**Comment by klepp0906** [comment]
Real life, you know how that goes >.<

Not to mention you guys chipped away at much of it till 7.1 hit anyways lol.

I'll do my best to split these up as soon as possible.   Got a new little baby that makes it hard to get anything done! Lol.

Btw the whole bit about "not showing in bugsack" was incorrect.  They show, it just has to be opened.  The minimap icon (whether it's on their or your end; is no longer turning red)

Sorry about the multi post I was just beginning to feel like a bother :p

**Comment by joev** [comment]
Hey @klepp0906 Thanks a mill for taking the time to split them up. Life with a small baby is tough I know... you do need some time for yourself! Come join us on Discord some times (if only for some stress relief :>) https://discord.gg/4VJdSsc

Closing this as you've split it into individual issues now. (thanks!)
