### ISSUE TITLE
Curse release seems to be missing some options in SVui.

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#151]
Brought to light by Discord user geriv

![options](https://cdn.discordapp.com/attachments/231735965419438080/355303013180506113/unknown.png)

![installed](https://cdn.discordapp.com/attachments/231735965419438080/355303874988605442/unknown.png)

I've replicated this from the release build on curse. 

Initial issue raised was regarding inability to move the new toast window. may have been handled badly by Curse?

Current repo build works fine in this regard.

**Comment by joeymagz** [comment]
Fixed in 1.4.2
