### ISSUE TITLE
Data dock size

### ISSUE THREAD

**Issue by klepp0906** [FailcoderAddons/supervillain-ui#16]
not really a bug but..

anyone notice the borders for the bottom and top data docks seem qutie a bit taller than they were before?

any chance we can get this reverted to the original height? or make it adjustable? It used to come about 1/2 way up the letters/numbers for the various items i have pinned. Now it covers them entirely almost like a viewport and much less like a border >.<

**Comment by joev** [comment]
You'll need to do a screenshot I think mate. Mine looks exactly the same (and correct) - The bars are 1/2 the height of the docklet buttons (Guild, Achievements, Chat window tabs, Spec Swap, Hearthstone etc.)  and 2/3rd the height of the reports (Rep, Artifact, XP bars etc) and any other SS's other people have posted recently seem fine too.

**Comment by klepp0906** [comment]
Yea mine are now completely covering my dps/artifact etc.  I'll ss it though and get back!

**Comment by joeymagz** [comment]
All of the docks are the correct size. This may be an issue between high resolution vs. low resolution. Please use the correct button during initial setup.
