### ISSUE TITLE
Garrison/orderhall panel buttons are hang too low

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#162]
![example](https://i.imgur.com/vgtzmJq.png)

They do follow the frame when moved but dangle far bellow the other panel

**Comment by finalsliver** [comment]
not sure what causes this, it's not consistent across logins

**Comment by immortaltech** [comment]
#129 same problem.
Zoned in/out few times
![1st](https://user-images.githubusercontent.com/7233566/30463998-5a80ee18-99a5-11e7-8741-8bf840e77503.jpg)
![2nd](https://user-images.githubusercontent.com/7233566/30464003-60d1a046-99a5-11e7-9c1c-6ba8c555e197.jpg)
![3rd](https://user-images.githubusercontent.com/7233566/30464008-67b072f2-99a5-11e7-82ed-ac883940b7c9.jpg)
