### ISSUE TITLE
LUA error 1

### ISSUE THREAD

**Issue by klepp0906** [FailcoderAddons/supervillain-ui#17]
1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_QuestTracker' tried to call the protected function 'CompactRaidFrame9:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:339: in function`CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:280: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:180: in function <FrameXML\CompactUnitFrame.lua:180>

Locals:

**Comment by joev** [comment]
@klepp0906 Next time you see this, can you have a look at previous errors in Bugsack (if there are any) and post as this doesn't have enough info for me to go on

**Comment by klepp0906** [comment]
I checked - didn't have any.  Will keep checking though and let ya know!

**Comment by joeymagz** [comment]
Closing since it was last reported in October and nothing since.
