### ISSUE TITLE
Craft O Matic lua erro

### ISSUE THREAD

**Issue by immortaltech** [FailcoderAddons/supervillain-ui#170]
2x SVUI_CraftOMatic\SVUI_CraftOMatic-1.0.09.lua:452: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
SVUI_CraftOMatic\SVUI_CraftOMatic-1.0.09.lua:452: in function `EndJobModes'
SVUI_CraftOMatic\SVUI_CraftOMatic-1.0.09.lua:529: in function <SVUI_CraftOMatic\SVUI_CraftOMatic.lua:528>

Locals:
(*temporary) = "UndeadExploration"

This happens everytime i click the '' Click to exit '' button in the fishing mode

**Comment by finalsliver** [comment]
@immortaltech are you using the latest version (either from curse/twitch or from here). if you are using the Curse/twitch version, please make sure you are only using [This one](https://mods.curse.com/addons/wow/supervillain-ui)

This was an issue we fixed shortly after 7.3 hit. 
looks fine and can't replicate.

**Comment by immortaltech** [comment]
I updated it, thanks.
Fixed
