### ISSUE TITLE
Supervillian UI Maps

### ISSUE THREAD

**Issue by Slyness69** [FailcoderAddons/supervillain-ui#171]
Message: Interface\AddOns\SVUI_Maps\SVUI_Maps.lua:229: attempt to index local 'iconFile' (a number value)
Time: 10/11/17 21:15:26
Count: 1480
Stack: Interface\AddOns\SVUI_Maps\SVUI_Maps.lua:229: attempt to index local 'iconFile' (a number value)
[C]: ?
Interface\AddOns\SVUI_Maps\SVUI_Maps.lua:229: in function <Interface\AddOns\SVUI_Maps\SVUI_Maps.lua:191>
Interface\AddOns\SVUI_Maps\SVUI_Maps.lua:265: in function `f'
...nterface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Timers.lua:61: in function <...nterface\AddOns\SVUI_!Core\libs\_SVUI_Lib\Timers.lua:52>

Locals: 

It works on a couple of characters but the rest of them it bugs out and I'm unable to see other addons such as Rarity, Vuhdo etc

**Comment by Slyness69** [comment]
Yes I have the latest version of Curse, which seemed to cause the problem. I downloaded the latest files from GitHub before they were available on Curse due to the original creator giving up on SVUI.  And they worked fine, but around a week ago curse had updates for SVUI and that's when the problem started. So I've downloaded the files from GitHub again this morning and it's resolved my issue, thanks for replying anyway

**Comment by finalsliver** [comment]
No worries. glad to know it was resolved :)

Out of Curiosity. were you using the all in one install on curse or the multiple individual downloads?

**Comment by Slyness69** [comment]
The multiple individual downloads

**Comment by finalsliver** [comment]
Thanks for confirming

The individual downloads are all old but we can't take them down till the original developer returns due to account issues. 

If you do want to use Curse to update then [this](https://mods.curse.com/addons/wow/supervillain-ui) is kept uptodate and all in one.
