### ISSUE TITLE
skin changes

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#179]
on death Recap button
Recap panel
![](https://i.imgur.com/pYisyE8.jpg)
Transmog panel 
![](https://i.imgur.com/Fhh5Hvq.png)

----
Achievements in achievement window (cycle from "achievements" tab to "guild" and back.) /reload repairs this temp.

![](https://i.imgur.com/5EMME1f.png)
![](https://i.imgur.com/GK4R3Lw.png)
![](https://i.imgur.com/ViUqsUM.png)

Results may vary. pic 2 and 3 are varients of output.

Adding more as I find them.

**Comment by Elowan** [comment]
thanks a lot, Joeymagz!
