### ISSUE TITLE
Show group on raidframes

### ISSUE THREAD

**Issue by Elowan** [FailcoderAddons/supervillain-ui#185]
hi there, is there an option, to show the number of groups on the raidframes?
If not, please consider implementing one!

Best Regards,

Elo

**Comment by finalsliver** [comment]
The option exists in the raid frame settings. 
![](https://i.imgur.com/IK0Z2HA.jpg)

**Comment by Elowan** [comment]
Ooops, I´ve missed it, it seems. Thank you for support !

**Comment by finalsliver** [comment]
If you have any questions in the future then please post about it in our Discord. it should get a quicker response. I'm not always online :p 
https://discord.gg/58AcatX

**Comment by Elowan** [comment]
nice - thanks for this information!
