### ISSUE TITLE
Lua error with unit frames

### ISSUE THREAD

**Issue by dnormX** [FailcoderAddons/supervillain-ui#199]
Getting a Lua error that seems to be preventing the unit frames from drawing.

UnitFrames [Load]: @(07/18/18 06:52:45) - ...e\AddOns\SVUI_UnitFrames\libs\oUF\elements\power.lua:110: Attempt to register unknown event "UNIT_POWER

Near the end of the install dialogue, the installer is blank, appears to be the same lua error?

(I'm not a programmer so this is probably wildly unhelpful but trying because I'm a fan.)

**Comment by blueberryiswar** [comment]
Can be fixed by uncommenting following lines (starting on line 110 of power.lua):
`
                -- error Attempt to register unknown even UNIT_POWER
		--self:RegisterUnitEvent("UNIT_POWER", unit);
		--self:RegisterUnitEvent("UNIT_MAXPOWER", unit);
`

**Comment by stygiansabyss** [comment]
Can also be fixed by changing any instance of UNIT_POWER to UNIT_POWER_UPDATE.  Patch changed the name of this value.
