### ISSUE TITLE
Warlock shards texture issue with UnitFrames

### ISSUE THREAD

**Issue by sorcerer-merlin** [FailcoderAddons/supervillain-ui#208]
UnitFrames [Load]: @(07/23/18 03:05:39) - ...e\AddOns\SVUI_UnitFrames\class_resources\warlock.lua:123: attempt to index field '?' (a nil value)

I get the fire animation but the shards just look like rocks. The textures are good as far as I can tell. Not sure what is causing it, my LUA fu is not that strong.

Anyway, I love this UI so thanks to all who are helping to revive it!!!!

**Comment by sorcerer-merlin** [comment]
P.S. Also seems to be an issue on my DK with RUNE_TYPE_UPDATE being undefined.

Again, Thanks!

**Comment by Teylu** [comment]
Same happens to the PriestOrbs
Hunters WildFire Infution have no visual bug but it's shown on every spec
