### ISSUE TITLE
potential minimap icon issue

### ISSUE THREAD

**Issue by klepp0906** [FailcoderAddons/supervillain-ui#21]
so far ive only noticed a problem w/ bugsack so it may be that icon itself that needs updating.  I figured since you guys resize/reskin stuff it may be on your end as well.

lua errors used to turn bugsack red.  It now stays green so i didnt realize I had them until i actually made an effort to open it. 

I did so due to getting an error on login popping up by itself when I dont have bugsack set to do that.

(it was this error fwiw)
SKINS [Blizzard_GuildUI]: @(10/27/16 18:55:49) - ...face\AddOns\SVUI_Skins\components\blizzard\guild.lua:524: attempt to call method 'SetStyle' (a nil value)

**Comment by joev** [comment]
That error is caught by the internal SVUI error/debugging handler before Bugsack gets it. This is normal behaviour.
