### ISSUE TITLE
UnitFrames [Load]: @(07/24/18 09:48:59) - ...UI_UnitFrames\libs\plugins\oUF_KungFu\oUF_KungFu.lua:280: Attempt to unregister unknown event "UPDATE_VEHICLE_ACTION_BAR

### ISSUE THREAD

**Issue by ItIsKelly** [FailcoderAddons/supervillain-ui#211]
UnitFrames [Load]: @(07/24/18 09:48:59) - ...UI_UnitFrames\libs\plugins\oUF_KungFu\oUF_KungFu.lua:280: Attempt to unregister unknown event "UPDATE_VEHICLE_ACTION_BAR

This issue only appears on my Monk. All other classes appear to be working. It causes the unitframes not to show up.

**Comment by finalsliver** [comment]
If I'm reading into this correctly both of those files are withing the oUF library which Joey is looking into updating. 
This should be handled by that over all update. 

This is however a good bandaid fix for monk players until that time.

I'll throw together a patch for it to cover till the future ouF update
