### ISSUE TITLE
rogue combo points issue

### ISSUE THREAD

**Issue by hoodedjuggalo** [FailcoderAddons/supervillain-ui#213]
UnitFrames [Load]: @(07/28/18 15:59:29) - ...ace\AddOns\SVUI_UnitFrames\class_resources\rogue.lua:110: attempt to index field '?' (a nil value)

**Comment by amm4108** [comment]
This issue was fixed in one of the recent pull requests, and can be closed. Rogues should be able to use the SVUI unit frames again.
