### ISSUE TITLE
Loading in after fresh install

### ISSUE THREAD

**Issue by rchelbig** [FailcoderAddons/supervillain-ui#231]
SKINS [CUSTOM_LFD]: @(12/13/18 16:14:40) - ...erface\AddOns\SVUI_Skins\components\blizzard\lfd.lua:185: attempt to index global 'PVEFrameTitleBg' (a nil value)

just loaded up the ui & got this error right away after doing the initial customization

**Comment by amm4108** [comment]
This issue and Issue #232 are the same issue as far as I can tell. Pull Request #233 fixes this.
