### ISSUE TITLE
LUA Error 

### ISSUE THREAD

**Issue by klchavez** [FailcoderAddons/supervillain-ui#232]
SKINS [CUSTOM_LFD]: @(01/01/19 04:49:28) - ...erface\AddOns\SVUI_Skins\components\blizzard\lfd.lua:185: attempt to index global 'PVEFrameTitleBg' (a nil value)

The line it's referencing is in bold.
I've tried a couple of minor changes but I don't know LUA so I don't want to try a manual fix.

  LFGDungeonReadyDialog:RemoveTextures()
  LFGDungeonReadyDialog:SetStyle("Frame", "Pattern", true, 2, 4, 4)

  PVEFrameLeftInset:RemoveTextures()
  RaidFinderQueueFrame:RemoveTextures(true)
  PVEFrameBg:Hide()
  **PVEFrameTitleBg:Hide()**
  PVEFramePortrait:Hide()
  PVEFramePortraitFrame:Hide()
  PVEFrameTopRightCorner:Hide()
  PVEFrameTopBorder:Hide()
  PVEFrameLeftInsetBg:Hide()
  PVEFrame.shadows:Hide()
  PVEFrame:EnableMouse(false)

**Comment by amm4108** [comment]
This bug has been fixed and is awaiting a merge.

**Comment by joeymagz** [comment]
Fixed
