### ISSUE TITLE
Lua error 3

### ISSUE THREAD

**Issue by klepp0906** [FailcoderAddons/supervillain-ui#24]
3x SVUI_Tooltip\SVUI_Tooltip-1.3.7.lua:530: attempt to call method 'GetAttribute' (a nil value)
SVUI_Tooltip\SVUI_Tooltip-1.3.7.lua:530: in function <SVUI_Tooltip\SVUI_Tooltip.lua:524>

Locals:
self = GameTooltipStatusBar {
 0 = <userdata>
 text = <unnamed> {
 }
 border = <unnamed> {
 }
}
value = 17503
tooltip = GameTooltip {
 0 = <userdata>
 SetHyperlink = <function> defined =[C](?):-1
 SetGuildBankItem = <function> defined =[C](?):-1
 Hide = <function> defined =[C](?):-1
 comparing = false
 SuperBorder = <unnamed> {
 }
 SetUnitDebuff = <function> defined =[C](?):-1
 SetLootItem = <function> defined =[C](?):-1
 SetQuestItem = <function> defined =[C](?):-1
 SetRecipeReagentItem = <function> defined =[C](?):-1
 InjectedDouble = <table> {
 }
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C](?):-1
 SetQuestLogItem = <function> defined =[C](?):-1
 SetTradeTargetItem = <function> defined =[C](?):-1
 SetTradePlayerItem = <function> defined =[C](?):-1
 SetSendMailItem = <function> defined =[C](?):-1
 updateTooltip = 0.10199999511242
 SetInventoryItem = <function> defined =[C](?):-1
 SetInboxItem = <function> defined =[C](?):-1
 SetLootRollItem = <function> defined =[C](?):-1
 SetUnitAura = <function> defined =[C](?):-1
 SetBuybackItem = <function> defined =[C](?):-1
 SetAuctionSellItem = <function> defined =[C](?):-1
 SetBagItem = <function> defined =[C](?):-1
 needsReset = true
 SetUnitBuff = <function> defined =[C](?):-1
 SetBackdropColor = <function> defined =[C](?):-1
 SetRecipeResultItem = <function> defined =[C](?):-1
 SetAuctionItem = <function> defined =[C](?):-1
}
unit = nil
mFocus = <unnamed> {
 0 = <userdata>
 messageInfo = <table> {
 }
}
(_temporary) = nil
(_temporary) = <unnamed> {
 0 = <userdata>
 messageInfo = <table> {
 }
}
(_temporary) = "unit"
(_temporary) = "attempt to call method 'GetAttribute' (a nil value)"
BAR_TEXT = true
select = <function> defined =[C](?):-1
format = <function> defined =[C](?):-1
floor = <function> defined =[C](?):-1
TAPPED_COLOR = <table> {
 b = 0.6
 g = 0.6
 r = 0.6
}
TruncateString = <function> defined @SVUI_Tooltip\SVUI_Tooltip.lua:165

**Comment by joev** [comment]
@klepp0906 What object in the world are you hovering your mouse over when this happens?

**Comment by klepp0906** [comment]
I didn't notice at the time and have yet to see it again (been busy this weekend ugh) but will try to be more attentive of said things and let ya know!  Going to put in some hours today :)

**Comment by klepp0906** [comment]
Hit close instead of submit, sry!

**Comment by joeymagz** [comment]
This bug should be resolved now.
