### ISSUE TITLE
I'm sure you guys are aware but artifact Ilvl is showing incorrect

### ISSUE THREAD

**Issue by klepp0906** [FailcoderAddons/supervillain-ui#26]
mine says 1024 at the moment w00t! lol (in character pane ftr)

**Comment by jbondpdx** [comment]
Yah, mine is like 968 and my artifact offhand is 750, which is quite sad (even knowing it's not right).

**Comment by joev** [comment]
Fixed. Now using same calls as Blizzard tooltip (so if it's wrong any more then it's deffo a blizz bug)
