### ISSUE TITLE
error popup upon login (doesnt show in bugsack?)

### ISSUE THREAD

**Issue by klepp0906** [FailcoderAddons/supervillain-ui#27]
SKINS [Blizzard_GuildUI]: @(10/30/16 08:48:23) - ...face\AddOns\SVUI_Skins\components\blizzard\guild.lua:524: attempt to call method 'SetStyle' (a nil value)

window pops up by itself and seems unrelated to bugsack as bugsack says i have no errors.

**Comment by joev** [comment]
Duplicate of #12
