### ISSUE TITLE
Mythic Challenge Tab Issue

### ISSUE THREAD

**Issue by PauloFranco** [FailcoderAddons/supervillain-ui#29]
The skin for the Mythic Challenge tab (hotkey i) is giving up errors.

`SKINS [Blizzard_ChallengesUI]: @(10/31/16 01:33:11) - ...AddOns\SVUI_Skins\components\blizzard\challenges.lua:24: attempt to index global 'ChallengesFrameDetails' (a nil value`

**Comment by joeymagz** [comment]
This has been resolved.
