### ISSUE TITLE
Class Order Hall Bar Overlap

### ISSUE THREAD

**Issue by zekethesquirrel** [FailcoderAddons/supervillain-ui#3]
![orderhalloverlap](https://cloud.githubusercontent.com/assets/1409081/19617367/feada2a4-97eb-11e6-83cd-ab33ab5f47f2.jpg)

The bar that appears at the top of the screen when you enter your class order hall currently overlaps the top bars on the screen. There are a few different ways I feel this could be handled.
- First would be to move the top border of SVUI down to position it below the class order hall bar when in an order hall.
- Another option would be to hide the order hall bar all together. There are a few other addons that can do this already, but I don't feel that it's the best way to handle this issue.
- My last suggestion would be to incorporate the order hall information into the top bar when in your order hall. This may not be the easiest option, or even feasible, but would certainly be appreciated.

**Comment by GotoR** [comment]
Also reporting weird behaviour of order hall bars and micro menu bar/minimap +auras.
Steps to reproduce:
1.  Login/reload ui outside class hall. Top part of your screen will be like that - everything is ok.
![1](https://cloud.githubusercontent.com/assets/4509516/20045206/342cc29a-a4b0-11e6-884e-1bded4dc3f40.png)
2.  Teleport to class hall - some UI elements will move down.
![2](https://cloud.githubusercontent.com/assets/4509516/20045222/533c5e5c-a4b0-11e6-8757-7e10fa34fcbb.png)
3. Teleport from class hall - UI elements are still lower than they should be as if class order hall bar is still present
![3](https://cloud.githubusercontent.com/assets/4509516/20045235/72d4c448-a4b0-11e6-8815-ba6672ab4429.png)

**Comment by joeymagz** [comment]
This is mostly fixed. Still working on getting the top/bottom bars to return after leaving the class order hall, but the map and everything returns to it's proper location.
