### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Murphy107j** [FailcoderAddons/supervillain-ui#32]
SKINS [Blizzard_GuildUI]: @(11/01/16 17:39:35) - ...face\AddOns\SVUI_Skins\components\blizzard\guild.lua:524: attempt to call method 'SetStyle' (a nil value

**Comment by Murphy107j** [comment]
Core [UI_SCALE_CHANGED]: @(11/01/16 17:58:52) - Interface\AddOns\SVUI_!Core\system\api.lua:1481: attempt to perform arithmetic on global 'testScale1' (a nil value) and this happens when i alt tab

**Comment by finalsliver** [comment]
Regarding the Second error reported here (starting; Core [UI_SCALE_CHANGED]:) 

Do you play full screen, windowed or Fullscreen(windowed) ?

**Comment by Murphy107j** [comment]
I play full screen and before the updates I wasn't getting these

**Comment by finalsliver** [comment]
I should have asked this in my previous inquiry. What version are you Running? 
Curse/WoWi versions?
or 
Github repo Version?

Last change on the github was 10hrs ago and has changed many times in the last 24hours. 

For reference atm. last commit ID: 6cfd0a4

**Comment by Murphy107j** [comment]
Right now curse but I have tried  both

**Comment by joev** [comment]
Fixed in the Repo. Haven't pushed this change to curse or WowI  yet (awaiting @failcoder to return to do so but his computer is acting up).

**Comment by joeymagz** [comment]
This has been fixed. Closing issue.
