### ISSUE TITLE
Micro Menu Bar

### ISSUE THREAD

**Issue by silenced24** [FailcoderAddons/supervillain-ui#37]
Micro Menu Bar now moving position on screen after you zone. A /reload does fix it. And the Guild button is still not skinning correctly.

**Comment by dasmall80** [comment]
I have been able to prevent noticeable movement on two of my characters.  Using MoveAnything I set the scale for the Order Hall Command Bar to 0.01 and disable the SVUI Skin option for Order Hall.

**Comment by joeymagz** [comment]
Fixed with and tied to #3
