### ISSUE TITLE
Can't mouseover minimap info

### ISSUE THREAD

**Issue by TiaMaster** [FailcoderAddons/supervillain-ui#4]
The minimap is acting as if something is in front of most of it.  Everywhere but in the last 20% of the minimap I am unable to mouseover things to get a tooltip telling me things like what icons are, or what a quest area requires.

**Comment by joev** [comment]
As per discussion on Discord.

Framestacks of problem area:
https://cdn.discordapp.com/attachments/231735965419438080/240290989971865600/unknown.png
https://cdn.discordapp.com/attachments/231735965419438080/240291330348023808/unknown.png

Working after pet battle (layout resets) 

https://cdn.discordapp.com/attachments/231735965419438080/240292574944821249/unknown.png

Looks like some elements of original minimap not being properly hidden/removed.

**Comment by joeymagz** [comment]
Does this still happen in the latest build? I'm not getting this anymore.
