### ISSUE TITLE
I'm getting this-and my options for Unit Frames are missing from the SVUI options.  

### ISSUE THREAD

**Issue by lkj61** [FailcoderAddons/supervillain-ui#51]
2x ...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:41: attempt to compare number with nil
...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:41: in function `ArtifactUI_CanViewArtifact'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:683: in function `EvaluateRelics'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:533: in function <...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:531>
[C]: in function `SetShown'
...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:172: in function `SetTab'
...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:138: in function `EvaulateForgeState'
...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:70: in function <...eBlizzard_ArtifactUI\Blizzard_ArtifactUI.lua:67>
[C]: in function `Show'
FrameXML\UIParent.lua:2374: in function `SetUIPanel'
FrameXML\UIParent.lua:2192: in function `ShowUIPanel'
FrameXML\UIParent.lua:2086: in function <FrameXML\UIParent.lua:2082>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2868: in function `ShowUIPanel'
FrameXML\UIParent.lua:1498: in function <FrameXML\UIParent.lua:907>

Locals:
(*temporary) = nil
(*temporary) = false
(*temporary) = "attempt to compare number with nil"

**Comment by WpPrRz** [comment]
Can confirm that UnitFrames have vanished from SVUI Settings after the update. The mod however still reflects as an installed addon.

**Comment by finalsliver** [comment]
check your interface/addons folder. there should only be one set of SVui addons installed. 
Further make sure you are on the latest build available from this repo. (green button on main page, download as Zip.) 

Not sure about the error, leave that for the boss

**Comment by WpPrRz** [comment]
Yeah, interface/addons looks good. No doubles of folders.

![addons](https://cloud.githubusercontent.com/assets/3228421/20190749/58989e14-a78b-11e6-8d4e-e54a64a44ace.PNG)

**Comment by lkj61** [comment]
Ditto.  No folder dupes.  But I did uninstall the latest from Curse and downloaded the zip from here and the settings are back.

**Comment by finalsliver** [comment]
Sorry to somewhat revive this post. @WpPrRz have you tried the Github repo build? 

Repo seems to have the fix for it :p

**Comment by WpPrRz** [comment]
@finalsliver 

Yup, currently using the Github version with zero issues except like 4 minor quality of life issues.

**Comment by joeymagz** [comment]
Closing this since it appears to be resolved.
