### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Murphy107j** [FailcoderAddons/supervillain-ui#56]
QuestTracker [WORLD_STATE_TIMER_START]: @(11/11/16 20:22:21) - ...ace\AddOns\SVUI_QuestTracker\components\scenario.lua:286: attempt to call upvalue 'GetChallengeModeMapTimes' (a nil value)

**Comment by Murphy107j** [comment]
Any luck on figuring this out it's annoying with doing mythic plus runs. I also havn't seen any updates done in over a month I am wondering if this have been abandoned.

**Comment by joeymagz** [comment]
This has been fixed.
