### ISSUE TITLE
Missing Fishing Rod from CraftOMatic

### ISSUE THREAD

**Issue by dasmall80** [FailcoderAddons/supervillain-ui#59]
Thruk's Fishing Rod
http://www.wowdb.com/items/120163-thruks-fishing-rod

Same increase as Staat's so probably equal weighting.

{ ["id"] = 120163, 	["weight"] = 3 	}, --Thruks

**Comment by finalsliver** [comment]
This should be  closeable now that the pole has been added.

**Comment by richy004** [comment]
Fixed in the latest updates
