### ISSUE TITLE
Independent Audio slider for chat alerts. 

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#6]
My poor ears. T.T

Mention alerts come through VERY loud. for some audio samples, painfully so. 
Could some audio control be added to this feature?

**Comment by finalsliver** [comment]
Covered by Joev in the Discord channel. 
add-ons not likely to be able to alter volume. will live without for now. 

Closing issue.

**Comment by finalsliver** [comment]
After discussing with @joev on Discord, Joev proposed to move the alerts to the FX channel rather than the master channel of audio.

This would provide better control of the audio distribution, allowing us to adjust all audio freely.

**Comment by joev** [comment]
Actually it would be great, hypothetically, if you could choose between Ambience, Dialog, Sound Effects, Music and Master channels....

**Comment by finalsliver** [comment]
New implementation works great. currently aligned to the FX channel for myself. :)
this covers my needs so closing issue.
