### ISSUE TITLE
Possible monk UI issue. 

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#61]
Interface\AddOns\SVUI_UnitFrames\elements\tags.lua:164: bad argument #1 to 'unpack' (table expected, got nil) 

Discord User nCode managed to find this error. unable to figure out source or replicate. 

Persisted after update to latest repo build, persisted UI reinstall.  

Occurred when on his monk after engaging in combat for a short time.

**Comment by joeymagz** [comment]
I've been playing on my monk a lot lately (leveling and running dungeons, lfr, etc.) and have been unable to reproduce this error.
