### ISSUE TITLE
Details appears to be working fine.

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#66]
https://github.com/FailcoderAddons/supervillain-ui/blob/d05f090bb6de8a6d72a15b465688ccab30854508/SVUI_Skins/components/docklet.lua

line 312 - > 336 (not familair enough with Github to make this easier to get to).

I've been using details with these lines 'uncommented' for about 4 months. not had any issues or errors pop up. Appears to be working fine at the moment. 

Sockets into the docket fine, Haven't had any bleed through or overlaps. Seems to perform fine. 

Only remembered to report this after having to amend the above file again as I updated to the latest repo version. :)

**Comment by richy004** [comment]
Pushed this into the master. Appears to be working fine
