### ISSUE TITLE
Inventory ilvl on relics

### ISSUE THREAD

**Issue by finalsliver** [FailcoderAddons/supervillain-ui#73]
Currently relic ilvl isn't displayed like other equipment. 

Normally, this ilvl is overlayed over the items icon in the bags. however, for relics this does not occur. 

Possibly related to #72  as both deal with relics.

**Comment by richy004** [comment]
This should now be fixed in the latest push. 

![image](https://cloud.githubusercontent.com/assets/13172408/23650957/05620f8e-0378-11e7-865a-925c8e58b16d.png)

**Comment by finalsliver** [comment]
Looking great so far, had some inconsistency with ilvl reported by some relics, but they were picked up during levelling so it's to be expected :)
