### ISSUE TITLE
Errors .Lua 

### ISSUE THREAD

**Issue by Kirito80** [FailcoderAddons/supervillain-ui#75]
61x ...aceSVUI_Skins\components\blizzard\system.lua:574: Usage: UnitIsUnit("unit", "otherUnit")
[C]: in function `UnitIsUnit'
...aceSVUI_Skins\components\blizzard\system.lua:574: in function <...aceSVUI_Skins\components\blizzard\system.lua:574>
[C]: ?
[C]: in function `Show'
FrameXML\ReadyCheck.lua:14: in function `ShowReadyCheck'
FrameXML\ReadyCheck.lua:51: in function <FrameXML\ReadyCheck.lua:49>

Locals:
(*temporary) = "player"
(*temporary) = nil

**Comment by finalsliver** [comment]
When did this error occur?

Also, is this from the repo build or from Curse/WoWinterface build?

**Comment by Kirito80** [comment]
The error occured two days ago. I have downloaded the addon from the link
 below:
https://github.com/FailcoderAddons/supervillain-ui.git

thx

2017-03-05 0:06 GMT+01:00 finalsliver <notifications@github.com>:

**Comment by finalsliver** [comment]
Sorry for my poor wording in the last response.

What was happening when the error occurred, was it on log in or when a specific event happens?

Has this happened since, and are you able to reproduce it?

any further info you are able to provide will help towards resolving this :)

**Comment by joeymagz** [comment]
Hey, I might have a fix for this one... self.initiator is being annoying in the ready check HookScript, so simple fix is this:

line 574 in SVUI_Skins\components\blizzard\system.lua
> ReadyCheckFrame:HookScript("OnShow", function(self) if self.initiator and UnitIsUnit("player", self.initiator) then self:Hide() end end)

added "self.initiator and" before "UnitIsUnit..." and the problem appears to have gone away... I only did minor testing (small group ready check out in the world, and lfr ready check...) but the problem appears to have gone away with that line.
