### ISSUE TITLE
BreakStuff.lua

### ISSUE THREAD

**Issue by joeymagz** [FailcoderAddons/supervillain-ui#79]
Final, here's one of the manual fixes for Prospecting and Milling. Thanks to hotluck on the forums, I expanded on what they did.

AllowedItemIDs - line 89 - I just added all Legion Ore's and Herbs.

> local AllowedItemIDs = {
		['109129']='OVERRIDE_MILLABLE', -- WoD herbs
		['109128']='OVERRIDE_MILLABLE', -- WoD herbs
		['109127']='OVERRIDE_MILLABLE', -- WoD herbs
		['109126']='OVERRIDE_MILLABLE', -- WoD herbs
		['109125']='OVERRIDE_MILLABLE', -- WoD herbs
		['109124']='OVERRIDE_MILLABLE', -- WoD herbs
		['124101']='OVERRIDE_MILLABLE', -- aethril
		['124102']='OVERRIDE_MILLABLE', -- dreamleaf
		['124104']='OVERRIDE_MILLABLE', -- fjarnskaggl
		['124103']='OVERRIDE_MILLABLE', -- foxflower
		['124105']='OVERRIDE_MILLABLE', -- starlight-rose
		['128304']='OVERRIDE_MILLABLE', -- yseralline-seed
		['109119']='OVERRIDE_PROSPECTABLE', -- WoD ore
		['123918']='OVERRIDE_PROSPECTABLE', -- leystone ore
		['123919']='OVERRIDE_PROSPECTABLE', -- felslate ore	
	}

Prospecting - line 305 - Removed code comments from before BreakStuff_Cache['OVERRIDE... 

>if(IsSpellKnown(31252)) then
		--print("Prospecting")
		allowed = true
		spellName,_ = GetSpellInfo(31252)
		BreakStuff_Cache[ITEM_PROSPECTABLE] = {spellName, 1, 0.33, 0.33}
		BreakStuff_Cache['OVERRIDE_PROSPECTABLE'] = {spellName, 1, 0.33, 0.33}
    local count = #spellListing + 1;
    spellListing[count] = spellName;
	end

**Comment by finalsliver** [comment]
This one is fixed and in, so should be native now, less to change :)

**Comment by richy004** [comment]
I believe this fix is in and should be working.
