### ISSUE TITLE
New error pops from 7.1 patch

### ISSUE THREAD

**Issue by DeviantJdm** [FailcoderAddons/supervillain-ui#8]
Skins [PLAYER_ENTERING_WORLD]: @(10/25/16 12:56:54) - ...rface\AddOns\SVUI_Skins\components\blizzard\chat.lua:204: attempt to call method 'RemoveTextures' (a nil value)

UnitFrames [BodyGuard] [UNIT_HEALTH]: @(10/25/16 12:58:36) - Interface\AddOns\SVUI_UnitFrames\bodyguard.lua:185: Usage: UnitName("unit")

UnitFrames [BodyGuard] [UNIT_HEALTH]: @(10/25/16 12:58:47) - Interface\AddOns\SVUI_UnitFrames\bodyguard.lua:185: Usage: UnitName("unit")

UnitFrames [BodyGuard] [UNIT_HEALTH]: @(10/25/16 12:59:16) - Interface\AddOns\SVUI_UnitFrames\bodyguard.lua:185: Usage: UnitName("unit")

UnitFrames [BodyGuard] [UNIT_HEALTH]: @(10/25/16 13:00:04) - Interface\AddOns\SVUI_UnitFrames\bodyguard.lua:185: Usage: UnitName("unit")

UnitFrames [BodyGuard] [UNIT_HEALTH]: @(10/25/16 13:00:47) - Interface\AddOns\SVUI_UnitFrames\bodyguard.lua:185: Usage: UnitName("unit")

UnitFrames [BodyGuard] [UNIT_HEALTH]: @(10/25/16 13:01:00) - Interface\AddOns\SVUI_UnitFrames\bodyguard.lua:185: Usage: UnitName("unit")

UnitFrames [BodyGuard] [UNIT_HEALTH]: @(10/25/16 13:01:02) - Interface\AddOns\SVUI_UnitFrames\bodyguard.lua:185: Usage: UnitName("unit")

UnitFrames [BodyGuard] [UNIT_HEALTH]: @(10/25/16 13:01:15) - Interface\AddOns\SVUI_UnitFrames\bodyguard.lua:185: Usage: UnitName("unit")

Skins [PLAYER_ENTERING_WORLD]: @(10/25/16 13:01:28) - ...rface\AddOns\SVUI_Skins\components\blizzard\chat.lua:204: attempt to call method 'RemoveTextures' (a nil value)

Skins [PLAYER_ENTERING_WORLD]: @(10/25/16 13:03:20) - ...rface\AddOns\SVUI_Skins\components\blizzard\chat.lua:204: attempt to call method 'RemoveTextures' (a nil value)

UnitFrames [BodyGuard] [UNIT_HEALTH]: @(10/25/16 13:03:37) - Interface\AddOns\SVUI_UnitFrames\bodyguard.lua:185: Usage: UnitName("unit")

Librarian:Events:TriggerOnce(LOAD_ALL_ESSENTIALS): [callback]: @(10/25/16 13:03:50) - Interface\AddOns\SVUI_!Core\system\debug.lua:395: attempt to call method 'SetStyle' (a nil value)

Librarian:Events:TriggerOnce(LOAD_ALL_ESSENTIALS): [callback]: @(10/25/16 13:03:50) - Interface\AddOns\SVUI_!Core\system\profile.lua:129: attempt to call method 'SetStyle' (a nil value)

**Comment by jbondpdx** [comment]
In addition to (some, but not all) of the above, I'm getting a chat error (and a misaligned chat window):

`Chat [Load]: @(10/25/16 11:30:25) - Interface\AddOns\SVUI_Chat\SVUI_Chat.lua:1100: ChatFrame1 doesn't have a "OnMessageScrollChanged" script`

**Comment by joev** [comment]
All of these errors now dealt with.
