### ISSUE TITLE
SVUI_Chat.lua

### ISSUE THREAD

**Issue by joeymagz** [FailcoderAddons/supervillain-ui#80]
Again, thanks to Hotluck on the forums...
This one fixes you mousing over an item or something in the chat window and the tooltip follows you all over the screen until you mouse over something different.

Replace _hook_OnHyperlinkLeave with...

> local _hook_OnHyperlinkLeave = function(self)
		if(not CHAT_HOVER_URL) then return; end
		HideUIPanel(GameTooltip)
		ACTIVE_HYPER_LINK = nil;
	end

It looks like whatever was changed prior to 7.1 was resulting in the refstring.match always returning nothing, so the old code only called the hyperlinkleave function when you moused over another game entity.

**Comment by richy004** [comment]
Committed and Pushed

Thanks for the fix.
