### ISSUE TITLE
new codes being thrown, too long to post in discord

### ISSUE THREAD

**Issue by DeviantJdm** [FailcoderAddons/supervillain-ui#85]
1491x ...aceSVUI_QuestTracker\components\scenario.lua:236: attempt to perform arithmetic on local 'maxTime' (a nil value)
...aceSVUI_QuestTracker\components\scenario.lua:236: in function `SetMedals'
...aceSVUI_QuestTracker\components\scenario.lua:325: in function <...aceSVUI_QuestTracker\components\scenario.lua:310>

Locals:
self = <unnamed> {
 0 = <userdata>
 StartTimer = <function> defined @SVUI_QuestTracker\components\scenario.lua:194
 UpdateBackdrop = <function> defined @SVUI_!Core\system\api.lua:554
 StopTimer = <function> defined @SVUI_QuestTracker\components\scenario.lua:212
 SetBackdropBorderColor = <function> defined =[C]:-1
 SetMedals = <function> defined @SVUI_QuestTracker\components\scenario.lua:225
 Panel = <unnamed> {
 }
 ___fadehandler = <unnamed> {
 }
 ___fadeset = <table> {
 }
 ___fademode = "IN"
 UpdateMedals = <function> defined @SVUI_QuestTracker\components\scenario.lua:249
 Icon = <unnamed> {
 }
 SetFrameLevel = <function> defined =[C]:-1
 Bar = <unnamed> {
 }
 UpdateChallenges = <function> defined @SVUI_QuestTracker\components\scenario.lua:289
 UpdateTimers = <function> defined @SVUI_QuestTracker\components\scenario.lua:310
 BackdropNeedsUpdate = true
}
elapsedTime = 201
blockHeight = 180
_ = "Neltharion's Lair"
_ = "party"
difficulty = 8
_ = "Mythic Keystone"
_ = 5
_ = 0
_ = false
mapID = 1458
zoneName = nil
_ = nil
maxTime = nil
(*temporary) = <table> {
}
(*temporary) = <userdata>
(*temporary) = 0
(*temporary) = 1
(*temporary) = 0.1
(*temporary) = "attempt to perform arithmetic on local 'maxTime' (a nil value)"
INNER_HEIGHT = 20
MOD = <table> {
 UnregisterUpdate = <function> defined @SVUI_!Core\libs\_SVUI_Lib\Registry.lua:509
 UpdateAchievements = <function> defined @SVUI_QuestTracker\components\achievements.lua:337
 InitializeBonuses = <function> defined @SVUI_QuestTracker\components\bonus.lua:435
 InitializeActive = <function> defined @SVUI_QuestTracker\components\active.lua:321
 UpdateObjectives = <function> defined @SVUI_QuestTracker\components\quests.lua:1059
 ToggleSharedData = <function> defined @SVUI_!Core\libs\_SVUI_Lib\Registry.lua:392
 LoadOptions = <function> defined @SVUI_QuestTracker\Loader.lua:41
 InitializePopups = <function> defined @SVUI_QuestTracker\components\popups.lua:208
 NameID = "SVUI [QuestTracker]"
 GetTimerTextColor = <function> defined @SVUI_QuestTracker\SVUI_QuestTracker.lua:341
 QuestItemTimer = "LOOP7"
 inMicroDungeon = false
 RegisterUpdate = <function> defined @SVUI_!Core\libs\_SVUI_Lib\Registry.lua:493
 CurrentQuest = 0
 ReLoad = <function> defined @SVUI_QuestTracker\SVUI_QuestTracker.lua:415
 public = <table> {
 }
 UpdateActiveObjective = <function> defined @SVUI_QuestTracker\components\active.lua:312
 Headers = <table> {
 }
 ___eventframe = <unnamed> {
 }
 Docklet = SVUI_QuestTracker {
 }
 IsSharingEnabled = <function> defined @SVUI_!Core\libs\_SVUI_Lib\Registry.lua:384
 ActiveQuestID = 0
 InitializeAchievements = <function> defined @SVUI_QuestTracker\components\achievements.lua:348
 CacheBonusObjective = <function> defined @SVUI_QuestTracker\components\bonus.lua:427
 media = <table> {
 }
 ChangeDBVar = <function> defined @SVUI_!Core\libs\_SVUI_Lib\Registry.lua:419
 CheckActiveQuest = <function> defined @SVUI_QuestTracker\components\active.lua:296
 UpdateLocals = <function> defined @SVUI_QuestTracker\SVUI_QuestTracker.lua:404
 UpdateScenarioObjective = <function> defined @SVUI_QuestTracker\components\scenario.lua:394
 UpdateBonusObjective = <function> defined @SVUI_QuestTracker\components\bonus.lua:421
 DOCK_IS_FADED = false
 UpdateDimensions = <function> defined @SVUI_QuestTracker\SVUI_QuestTracker.lua:357
 InitializeQuests = <function> defined @SVUI_QuestTracker\components\quests.lua:1209
 ___svfiles = <table> {
 }
 IgnoreSharedKeys = <function> defined @SVUI_!Core\libs\_SVUI_Lib\Registry.lua:402
 CombatLocked = false
 InitializeScenarios = <function> defined @S

**Comment by joeymagz** [comment]
I have a fix for this.

scenario.lua - Replace SetChallengeMedals function with this:

> local SetChallengeMedals = function(self, elapsedTime, ...)
	self:SetHeight(INNER_HEIGHT);
	local blockHeight = MOD.Headers["Scenario"].Block:GetHeight();
	local _, _, difficulty, _, _, _, _, mapID = GetInstanceInfo();
	local cmID = C_ChallengeMode.GetActiveChallengeMapID();
	MOD.Headers["Scenario"].Block:SetHeight(blockHeight + INNER_HEIGHT + 4);
	self:FadeIn();
	self.Bar:SetMinMaxValues(0, elapsedTime);
	self.Bar:SetValue(elapsedTime);

	if(cmID and difficulty == 8) then
		local zoneName, _, maxTime = C_ChallengeMode.GetMapInfo(cmID);
		MEDAL_TIMES[1] = maxTime * 0.6; -- 3 chest
		MEDAL_TIMES[2] = maxTime * 0.8; -- 2 chest
		MEDAL_TIMES[3] = maxTime -- 1 chest
	else
		for i = 1, select("#", ...) do
			MEDAL_TIMES[i] = select(i, ...);
		end
	end
	LAST_MEDAL = nil;
	self:UpdateMedals(elapsedTime);
end

**Comment by joeymagz** [comment]
I tested my fix in about 6 mythic+'s tonight and 0 issues.
