### ISSUE TITLE
LUA Error happening since 7.2. Happens upon login and when moving anything in my bag(s)

### ISSUE THREAD

**Issue by Lagwrath** [FailcoderAddons/supervillain-ui#87]
Message: Interface\FrameXML\MainMenuBar.lua:125: Usage: local cost = C_ArtifactUI.GetCostForPointAtRank(rank, tier)
Time: Wed Apr  5 19:25:40 2017
Count: 277
Stack: [C]: in function `GetCostForPointAtRank'
Interface\FrameXML\MainMenuBar.lua:125: in function <Interface\FrameXML\MainMenuBar.lua:123>
...ore\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:232: in function <...ore\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:223>
...ore\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:247: in function <...ore\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:243>
...ore\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:322: in function `?'
...ore\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:68: in function <...ore\libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:68>

Locals: (*temporary) = 41
(*temporary) = nil

Total of 15 pages of LUA errors. I can work on pasting them all in here if needed.

**Comment by joeymagz** [comment]
This is fixed with the latest commits. Please download the entire new package, and do a clean install.
