### ISSUE TITLE
Bubbles.lua Addon Taint

### ISSUE THREAD

**Issue by joeymagz** [FailcoderAddons/supervillain-ui#91]
817x SVUI_Chat\components\bubbles.lua:35: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `GetName'
SVUI_Chat\components\bubbles.lua:35: in function <SVUI_Chat\components\bubbles.lua:32>
SVUI_Chat\components\bubbles.lua:77: in function <SVUI_Chat\components\bubbles.lua:71>

**Comment by AiApaec** [comment]
I'm still getting this bug.. only when inside an instance though. Not before but still get it if I exit from the instance.

**Comment by joeymagz** [comment]
Removed the call to bubbles
